bloodpressure <- read.csv("~/Desktop/School/6304/Data Sets/ASCII-comma/CH06/ex6-5.TXT", quote="'")
bloodpressure.split <- split(bloodpressure$BloodPressure, bloodpressure$Temp)
qqnorm(bloodpressure.split$`5`, main = 'Normal Q-Q Plot: 5')
qqline(bloodpressure.split$`5`)
qqnorm(bloodpressure.split$`26`, main = 'Normal Q-Q Plot: 26')
qqline(bloodpressure.split$`26`)
var.5 <- var(bloodpressure.split$`5`)
var.26 <- var(bloodpressure.split$`26`)
print(sqrt(var.5))
print(sqrt(var.26))
bloodpressure.tTest <- t.test(bloodpressure$BloodPressure~bloodpressure$Temp, alternative = "greater", var.equal = T, conf.level = 0.95)
print(bloodpressure.tTest)